#!/bin/env bash
alias grep="grep --color"
alias egrep="egrep --color"

alias tailf="tail -f"

alias l="ls"
alias la="ls -a"
alias ll="ls -lah"

alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"

alias r="rails"
alias rk="rake"
alias b="bundle"
alias u="unicorn"

alias unicorn_start="bundle exec unicorn -c config/unicorn.rb -D"
alias unicorn_reload="kill -USR2 \$(cat tmp/pids/unicorn.pid)"
alias unicorn_stop="kill \$(cat tmp/pids/unicorn.pid)"

alias pull="git pull"
alias push="git push"
alias rebase="git rebase"

alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
