#!/bin/env bash
alias grep="grep --color"
alias egrep="egrep --color"

alias tailf="tail -f"

alias l="ls"
alias la="ls -a"
alias ll="ls -lah"

alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"

alias r="rails"
alias rk="rake"
alias b="bundle"
alias u="unicorn"

alias gh="github"
alias pull="git pull"
alias push="git push"
alias rebase="git rebase"

alias lock="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
