#!/bin/env bash

# editor
if command -v mvim > /dev/null; then
  export EDITOR="mvim -f"
else
  export EDITOR="vim"
fi

# colors
export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
export GREP_COLOR="4;33"

# projects
export CDPATH=$CDPATH:$HOME/Code
