#!/bin/env bash
if [ ! -d $HOME/.brew ]; then
  return
fi

export PATH=$HOME/.brew/bin:$PATH

# bash-completion
if [ -f $HOME/.brew/etc/bash_completion ]; then
  source $HOME/.brew/etc/bash_completion
fi

# node
if [ -d $HOME/.brew/lib/node ]; then
  export NODE_PATH=$HOME/.brew/lib/node
fi
