#!/bin/env bash

# attach homebrew bin path
if [ -d $HOME/.brew/bin ]; then
  export PATH=$HOME/.brew/bin:$PATH
fi

# bash-completion
if [ -f $HOME/.brew/etc/bash_completion ]; then
  source $HOME/.brew/etc/bash_completion
fi

# node.js
if [ -d $HOME/.brew/lib/node ]; then
  export NODE_PATH=$HOME/.brew/lib/node
fi
