#!/usr/bin/env bash

# Link our dotfiles
mkdir -p ~/.ssh

ln -si $PWD/bash_profile ~/.bash_profile
ln -si $PWD/gemrc ~/.gemrc
ln -si $PWD/gitignore ~/.gitignore
ln -si $PWD/irbrc ~/.irbrc
ln -si $PWD/screenrc ~/.screenrc
ln -si $PWD/sshrc ~/.ssh/rc

# Bootstrap the git configuration
# For reference, see http://git-scm.com/docs/git-config.html
git config --global alias.amend "commit --amend"
git config --global color.ui auto
git config --global core.excludesfile ~/.gitignore
git config --global help.autocorrect 1
git config --global push.default simple
