#!/bin/env bash
ln -si $PWD/bash_profile ~/.bash_profile
ln -si $PWD/gemrc ~/.gemrc
ln -si $PWD/gitignore ~/.gitignore
ln -si $PWD/screenrc ~/.screenrc

git config --global core.excludesfile ~/.gitignore
