#!/usr/bin/env bash
# See http://apple.stackexchange.com/questions/151986/change-mac-address-in-os-x-yosemite
spoof () {
  sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z
  sudo ifconfig en0 ether $(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/./0/2; s/.$//')
  networksetup -detectnewhardware
}
